### ISSUE TITLE
[TODO #1]: Add activation functions

### ISSUE THREAD

**Issue by SukritTM** [The5thAxiom/parallel-neural-networks#4]
- [x] We need a bunch of activation functions (priority to ReLU and sigmoid)
- [x] Each function must be overloaded to work on integers, floats, and matrices
- [x] Overloaded function will return the same type as its input (e.g. float function(float number), int function(int number), etc)
- [x] For matrices, the function must be run on every element of the matrix, and return a new matrix that has the outputs as its elements
- [x] We also need to implement the derivatives of each of these activations, following the same rules prescribed above

**Comment by The5thAxiom** [comment]
done!
