### ISSUE TITLE
[TODO #2]: Add layers

### ISSUE THREAD

**Issue by SukritTM** [The5thAxiom/parallel-neural-networks#5]
- [ ] Implement layers as a struct consisting of a matrix of weights, an input shape, an output shape, and an activation function
- [ ] [OPTIONAL] Validate that the dimensions of the shape are vectors
- [ ] Implement layer functions to:
        * Initialise the layer with random weights, based on input and output shape
        * Assign a matrix as the layer's weight, validated based on input and output shape
        * Change the input and output shapes
        * Assign an activation function, (can be part of init)
        * Have empty forward and backward pass functions (for later implementation)
