### ISSUE TITLE
[TODO #3]: Implement forward pass and MLP

### ISSUE THREAD

**Issue by SukritTM** [The5thAxiom/parallel-neural-networks#6]
- [ ] Implement model struct, as an ordered list of layers (Use linked list?)
- [ ] Function to add a layer to a model
- [ ] Implement forward pass function for a layer
- [ ] Implement a special input layer type?
- [ ] Implement the forward pass for the entire layer 
As can be seen I am not as clear on this, basically just make models work for forward pass
